"""
ExecutionBackend — abstract interface for isolated code execution environments.

Implementations
---------------
    ContainerBackend  — Docker-based ephemeral containers  (this sprint)

Future
------
    FirecrackerBackend — microVM isolation (post-MVP)

Lifecycle contract
------------------
Every backend MUST follow this lifecycle for every execution:

    backend.prepare(workspace)                       # may be a no-op
    try:
        result = backend.execute(workspace, entry_point, timeout_seconds,
                                 env_file, abort_signal, container_name)
    finally:
        backend.cleanup(workspace)                   # unconditionally called, must not raise

All implementations MUST:
  - Enforce the timeout (kill the process/container if exceeded)
  - Return a bounded ExecutionResult (no unbounded raw output)
  - Call cleanup even on error or timeout
  - Disable network access
  - Restrict writes to workspace only

Secret injection
----------------
  - env_file is an optional path to a Docker --env-file produced by SecretInjector.
  - Backends must NOT read, log, or persist the env_file contents.

Abort control
-------------
  - abort_signal is an optional threading.Event set by RevocationManager.
  - When set, the backend must stop the running process as soon as possible.
  - container_name is passed from RunnerAPI for abort observability and Docker stop.
"""

from __future__ import annotations

import threading
from abc import ABC, abstractmethod
from typing import Optional

from .execution_result import ExecutionResult


class ExecutionBackend(ABC):
    """Abstract isolated execution environment."""

    @abstractmethod
    def prepare(self, workspace_path: str) -> None:
        """
        Prepare the execution environment before execute().

        May be a no-op (e.g. ephemeral containers need no warm-up).
        Must not raise unless the environment is fundamentally unavailable.
        """
        ...

    @abstractmethod
    def execute(
        self,
        workspace_path: str,
        entry_point: str,
        timeout_seconds: int,
        env_file: str = "",
        abort_signal: Optional[threading.Event] = None,
        container_name: str = "",
    ) -> ExecutionResult:
        """
        Execute entry_point inside the isolated environment.

        Parameters
        ----------
        workspace_path  : absolute path to the workspace root on the host
        entry_point     : filename (relative to workspace/input/) to run
        timeout_seconds : wall-clock kill limit
        env_file        : path to a Docker --env-file (ephemeral secrets).
                          Empty = no secrets.  Backend must NOT read/log contents.
        abort_signal    : threading.Event set by RevocationManager to signal abort.
                          None = no revocation support for this execution.
        container_name  : container name/ID pre-generated by RunnerAPI.
                          Empty = backend generates its own name.

        Returns
        -------
        ExecutionResult — always returned, even on timeout or internal error.
        """
        ...

    @abstractmethod
    def cleanup(self, workspace_path: str) -> None:
        """
        Unconditional teardown. Called in a finally block — must not raise.

        Container-based backends: container is auto-removed (--rm); this may be a no-op.
        """
        ...
